#:schema node_modules/wrangler/config-schema.json
name = "image-proxy"
main = "src/index.ts"
compatibility_date = "2026-02-14"

[vars]
CLOUD_NAME = "dtdjjebzm"

# Routes: img2.findrefurbished.com/*
# Route: img2.findrefurbished.com/*
# Doel: Proxy images to Cloudinary CDN with auto format and caching