#:schema node_modules/wrangler/config-schema.json
name = "image-proxy"
main = "src/index.ts"
compatibility_date = "2026-02-14"

[vars]
CLOUD_NAME = "dtdjjebzm"

[env.preview]
name = "image-proxy-dev"
[env.preview.vars]
CLOUD_NAME = "dtdjjebzm"

[env.production]
name = "image-proxy"
[env.production.vars]
CLOUD_NAME = "dtdjjebzm"